### ISSUE TITLE
Problem to run this project

### ISSUE THREAD

**Issue by rafaelcavalcanti** [saxulum/saxulum#1]
Hi, excuse but when i run into 'composer.phar create-project saxulum/saxulum myproject --stability="dev"' i got some problems:

 Problem 1
    - Installation request for symfony/icu v1.2.1 -> satisfiable by symfony/icu[v1.2.1].
    - symfony/icu v1.2.1 requires lib-icu >=4.4 -> the requested linked library icu has the wrong version installed or is missing from your system, make sure to have the extension providing it.
  Problem 2
    - symfony/icu v1.2.1 requires lib-icu >=4.4 -> the requested linked library icu has the wrong version installed or is missing from your system, make sure to have the extension providing it.
    - symfony/intl v2.4.5 requires symfony/icu ~1.0-RC -> satisfiable by symfony/icu[v1.2.1].
    - Installation request for symfony/intl v2.4.5 -> satisfiable by symfony/intl[v2.4.5].

How can i solve this?
Thanks

**Comment by dominikzogg** [comment]
@rafaelcavalcanti Hello, cool you try to use my skeleton. Should be fixed now

**Comment by rafaelcavalcanti** [comment]
@dominikzogg i liked your project. Its a good one. But unfortunately i cant run. Thanks for answer.

**Comment by dominikzogg** [comment]
@rafaelcavalcanti Thx, do you still got same error?

**Comment by rafaelcavalcanti** [comment]
@dominikzogg I got another error, but its a wrong version of this library ICU that symfony is  requesting. I'm trying yet. Thanks for answer.

**Comment by dominikzogg** [comment]
@rafaelcavalcanti can i close this ticket, or are there still problems?

**Comment by rafaelcavalcanti** [comment]
Hello, how are you? yes you can close this ticket, i already fixed that issues and finally could run my project. Really thanks for the attention. Best regards.

Cordialmente
Rafael C. Cavalcanti

Alternativa Eco - Indústria de Produtos da Construção Civil ME
Website: www.alternativaeco.com
CNPJ: 07.092.397/0001-38
Endereço: Estrada Guaiapó, s/n, lote 228-a, Gleba Ribeirão Sarandi, Maringá - PR
Telefones: (44) 9167.1021 - VIVO / (44) 9761.7635 - TIM

Date: Wed, 5 Aug 2015 03:51:14 -0700
